Basic functionality implemented.  Not fully tested.

diff --git a/installkSNP b/installkSNP
--- a/installkSNP
+++ b/installkSNP
@@ -25,8 +25,8 @@ IGNOREME
 ######################
 ######################
 
-# Filename of the archive that contains the remaining scripts
-ARCHIVE=kSNP4.0.tgz
+# The other binaries are all in the kSNP4 directory once it is unpacked.
+ARCHIVE=kSNP4
 
 # Default install paths:
 # This is the directory where distribution files will be stored.  They may be
@@ -38,8 +38,10 @@ PACKAGEDIR=/usr/local/kSNP4Pkg
 BINDIR=/usr/local/bin
 
 # Variables containing lists of files that are required for kSNP to function
-USERBINS=kSNP4 Kchooser MakeKSNP4infile extractNthLocus4 rmNodeNamesFromTree4
-ALLBINS=add_paths3 buildtree CheckFileNames checkGenbankFromNCBI consense core_SNPs3 delete_allele_conflicts4 distance_tree3 extractNthLocus4 FastTreeMP find_snps find_unresolved_clusters3 fixOldFastaHeaders force_binary_tree genome_names3 getFastaGenomes get_filtered_kmers get_genbank_file4 getGenomeDataByAccession guessPartition inline_frequency_check jellyfish Kchooser4 kSNP4 ksnp-cache ksnpCache labelTree_AlleleCount-new3 label_tree_nodes3 LE2Unix make_file2genome MakeKSNP4infile mergeFastaReads merge_fasta_reads3 mummer NodeChiSquare2tree3 NodeChiSquare2tree4 number_SNPs_all3 number_SNPs_all4 ParAnn parse_assembly_summary parse_mummer4kSNP3 parseNCBIcsv parse_SNPs2VCF3 parsimonator partitionKmers rc_kmer_freqs3 rename_from_table3 renumber_probes3 rmNodeNamesFromTree4 selectNodeAnnotations4 SNPs2fastaQuery3 SNPs2nodes-new3 SNPs_all_2_fasta_matrix3 snpsort statusupdate subset_SNPs_all3 summarize_annotation tree_nodes3
+USERBINS="kSNP4 Kchooser MakeKSNP4infile extractNthLocus4 rmNodeNamesFromTree4 ksnpConfig"
+
+# A program to manipulate the kSNP configuration (if any)
+RECONFIGURE=ksnpConfig
 
 
 ######################
@@ -50,18 +52,131 @@ ALLBINS=add_paths3 buildtree CheckFileNames checkGenbankFromNCBI consense core_S
 ######################
 ######################
 
-# tar -C "${PACKAGEDIR}" "${ARCHIVE}"
+SYMLINKS=TRUE
+CONFIGURE=TRUE
+INSTALL=TRUE
+CMDLINE_ERROR=FALSE
+USAGE=FALSE
 
-for BINARY in ${ALLBINS}
+
+while [ ${#} -gt 0 ]  # While we have more arguments to process...
 do
-	cp "${BINARY}" "${PACKAGEDIR}/"
-done
+    case "${1}" in    # "switch" / case  based on what the argument is.
+	--symlinks-only) # This is used if the binaries are already in place.
+	    INSTALL=FALSE
+	    CONFIGURE=FALSE
+	    shift
+	    ;;
+
+	--configure-only) # This is used if we just want to re-configure.
+	    INSTALL=FALSE
+	    SYMLINKS=FALSE
+	    shift
+	    ;;
+
+	--install-only) # This is used if the user wants to place the symlinks and configure themselves.
+	    SYMLINKS=FALSE
+	    CONFIGURE=FALSE
+	    shift
+	    ;;
+	
+	--installdir)
+	    PACKAGEDIR="${2}"
+	    shift 2 # Argument and value
+	    ;;
+
+	--bindir)
+	    BINDIR="${2}"
+	    if [ ! -d "${BINDIR}" ]
+	    then
+		CMDLINE_ERROR=TRUE
+		echo "Specified target directory ${BINDIR} for binary symlinks does not yet exist."
+		echo "Did you specify the directory correctly?"
+	    fi
+	    shift 2
+	    ;;
+	
+	--help)
+	    USAGE=TRUE
+	    break
+	    ;;
+
+	--debug)
+	    DEBUG=1
+	    # Same as specifying -x on the shell shebang above.
+	    set -o xtrace
+	    # Same as specifying -v on the shell shebang above.
+	    set -o verbose
+	    shift # Argument
+	    ;;
+
+	*)  # All other values are errors.          
+	    CMDLINE_ERROR=TRUE
+	    USAGE=TRUE
+	    echo "Error: Unrecognized argument (no valid argument: ${1})"
+	    shift
+	    ;;
+    esac
+
+done # Processing arguments
+
+if [ "${USAGE}" = "TRUE" ]
+then
+    cat <<HERETEXT
+Usage: installkSNP [--bindir <directory in PATH>] [--installdir <install target>] [--install-only] [--symlinks-only] [--configure-only] [--help] [--debug]
+
+This script is designed to install and initially configure kSNP for your use.
+You likely will need to run it as an administrator to install to the default
+systemwide folders / directories.
+
+Optional arguments:
+ --bindir <directory>    Directory to place symbolic links to kSNP binaries.
+ --installdir <directory>  Directory to place kSNP binaries and support data.
+ --install-only          Instruct the script to only install binaries without
+                         placing symbolic links or configuring kSNP.
+ --symlinks-only         Replace symbolic links into the --bindir directory.
+ --configure-only        Configure kSNP for the current user, no installation.
+ --help                  This text.
+ --debug                 Verbose debugging information.  Probably useless.
 
 
-for BINARY in $USERBINS
-do
+Typical usage is to run without arguments.  You may also use it to re-
+configure kSNP from the defaults, or to restore the symbolic links if
+something happened to disturb them (like another kSNP install)
+HERETEXT
+    # And after displaying help, don't do anything.
+    exit 0
+fi
+
+
+if [ "${CMDLINE_ERROR}" = "TRUE" ]
+then
+   exit 1 # Error
+fi
+
+
+if [ "${INSTALL}" = "TRUE" ]
+then
+    mkdir -p "${PACKAGEDIR}"
+    cp "${ARCHIVE}/*" "${PACKAGEDIR}/"
+    # Make this installer available going forward.
+    cp "${0}" "${PACKAGEDIR}/"
+fi
+
+
+if [ "${SYMLINKS}" = "TRUE" ]
+then
+    
+    for BINARY in ${USERBINS}
+    do
 	ln -s "${PACKAGEDIR}/${BINARY}" "${BINDIR}/${BINARY}"
-done
+    done
+fi
+
+if [ "${CONFIGURE}" = "TRUE" ]
+then
+    "${PACKAGEDIR}/${RECONFIGURE}"
+fi
 
 
 
