Added start of caching, removed -all_annotations legacy option and references to annotate_SNPs_from_genbank3.
Also added some newer python implementations of legacy perl.

--HG--
branch : makefile

diff --git a/kSNP4 b/kSNP4
--- a/kSNP4
+++ b/kSNP4
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -vx
 
 ########################################################################
 
@@ -39,13 +39,14 @@ export ADD_PATHS="${KSNPPATH}/add_paths3"
 export LE2UNIX="${KSNPPATH}/LE2Unix"
 export CHECKFILENAMES="${KSNPPATH}/CheckFileNames"
 export MERGE_FASTA_READ="${KSNPPATH}/merge_fasta_reads3"
-export JELLYFISH="${KSNPPATH}/jellyfish"
+# export JELLYFISH="${KSNPPATH}/jellyfish"
+export JELLYFISH="jellyfish"
 export GETQUANTILE="${KSNPPATH}/get_quantile3"
-export SUBSETMERS="${KSNPPATH}/subset_mers3"
+export SUBSETMERS="${KSNPPATH}/subset_mers4"
 export DELETEALLELECONFLICTS="${KSNPPATH}/delete_allele_conflicts3"
 export PARALLELCOMMANDS="${KSNPPATH}/parallel_commands3"
-export SUBSETMERLIST="${KSNPPATH}/subset_mer_list3"
-export SUBSETSNPSALL="${KSNPPATH}/subset_SNPs_all3"
+export SUBSETMERLIST="${KSNPPATH}/subset_mer_list4.py"
+export SUBSETSNPSALL="${KSNPPATH}/subset_SNPs_all4"
 export SNPSTOFASTAQUERY="${KSNPPATH}/SNPs2fastaQuery3"
 export PICKSNPSFROMKMERS="${KSNPPATH}/pick_snps_from_kmer_genome_counts3"
 export FINDALLELE="${KSNPPATH}/find_allele3"
@@ -67,12 +68,12 @@ export LABELTREEALLELECOUNT="${KSNPPATH}/labelTree_AlleleCount-new3"
 export SNPMATRIXTODIST="${KSNPPATH}/SNP_matrix2dist_matrix3"
 export DISTANCETREE="${KSNPPATH}/distance_tree3"
 export FINDUNRESOLVEDCLUSTERS="${KSNPPATH}/find_unresolved_clusters3"
-export GETGENBANKFILE="${KSNPPATH}/get_genbank_file3"
+export GETGENBANKFILE="${KSNPPATH}/get_genbank_file4"
 export ANNOTATESNPFROMGENBANK="${KSNPPATH}/annotate_SNPs_from_genbankFiles3"
 export PARSEPROTEINANNOTATIONCOUNTS="${KSNPPATH}/parse_protein_annotation_counts3"
 export PARANN="${KSNPPATH}/ParAnn"
 export BUILDTREE="${KSNPPATH}/buildtree"
-
+export SUMMARIZEANNOTATION="${KSNPPATH}/summarize_annotation.py"
 
 
 
@@ -103,6 +104,8 @@ export ANNOTATELISTHEADERS="headers."${ANNOTATELIST}""
 
 export FASTALIST="fasta_list"
 export MINIMUMK=9 # The minimum acceptable value of K
+export CACHESIZE=10000000000 # Default cache size is 10G
+export CACHEDIR="" # Default cache directory is null / no caching.
 
 
 
@@ -246,11 +249,6 @@ do
 	    shift 2 # Argument and value
 	    ;;
 	
-	-all_annotations)
-	    ALL_ANNOTATIONS=1
-	    shift # Argument
-	    ;;
-	
 	-core)
 	    CORE=1
 	    shift # Argument
@@ -269,6 +267,22 @@ do
 	-vcf)
 	    VCF=1
 	    shift # Argument
+	    ;;
+
+	-cachedir)
+	    if [ -z "${CACHEDIR}" ]
+	    then
+		CACHEDIR=`"${ADD_PATHS}" "${2}" "${THISDIR}"`
+	    else
+		CMDLINE_ERROR=1
+		echo "Error: -cachedir cannot be specified more than once."
+	    fi
+	    shift 2
+	    ;;
+
+	-nocache)
+	    CACHEDIR=""
+	    shift
 	    ;;
 
 	-debug)
@@ -322,12 +336,6 @@ Optional arguments:
 			 existing analysis. Assumes only the new genomes are 
 			 listed in the -in file.
 
- -all_annotations  	 Annotate each locus exhaustively with all annotations 
- 			 in any of the annotated genomes. Without this option it
-			 only provides the first annotation it comes to for a
-			 given locus, checking in the order genomes are listed in
-			 the -annotate file.
-
  -core	                 Calculate core SNPs and core SNP parsimony tree
  -ML	                 Calculate Maximum Likelihood tree
  -genbank <genbank.gbk>	 Source file for SNP annotation
@@ -335,6 +343,9 @@ Optional arguments:
  -NJ  			 Calculate a neighbor joining tree
  -vcf			 Create a vcf file using the first genome specified in 
  			 the -positions file as the reference genome
+ -cache <cache dir>      Cache kSNP data to improve performance across runs.
+ -nocache      		 Disable all caching (this is the default)
+
 
 USAGE
 
@@ -368,6 +379,7 @@ then
     echo "NJ=${NJ}"
     echo "VCF=${VCF}"
     echo "DEBUG=${DEBUG}"
+    echo "CACHEDIR=${CACHEDIR}"
 fi
 
 
@@ -394,6 +406,14 @@ then
 fi
 cd "${DIR}"
 
+
+# If a cache directory was specified and does not exist, create it
+if [ -n "${CACHEDIR}" -a ! -d "${CACHEDIR}" ]
+then
+    mkdir -p "${CACHEDIR}" || { echo "Unable to create cache directory ${CACHEDIR}, continuing without cache." ; CACHEDIR="" ; }
+fi
+
+
 # This validation should be to STDERR, and shouldn't use state?  Or maybe the errors are
 # complicated enough that we need to keep the details around for the user to use to address
 # the errors?  TODO FIXME XXX
@@ -414,12 +434,6 @@ echo "input fasta_list: ${FASTALISTINPUT}"
 echo "output / working directory: ${DIR}"
 echo "k=${K}"
 echo "annotate_list file: ${ANNOTATELISTINPUT}"
-if [ 1 -eq "${ALL_ANNOTATIONS}" ]   # Defaults to 0
-then 
-	echo "Report all annotations"
-else
-	echo "Report minimal annotations"
-fi
 
 if [ -n "${MIN_FRACTION_WITH_LOCUS}" ]  # Defaults to empty string.
 then
@@ -1183,44 +1197,7 @@ then
     done
     
 	
-    cat genbank_from_NCBI.gbk.* | grep -v BioProject  > genbank_from_NCBI.gbk
-
-
-    # The annotate_SNPs_from_genbankFiles3 is a complicated script; deserves review / commenting. TODO - JN
-    if [ -e "${GENBANKFILEINPUT}" ]
-    then
-	"${ANNOTATESNPFROMGENBANK}"   -all "${ALL_ANNOTATIONS}" "${GENBANKFILEINPUT}" || true # This program returns an error regardless of success / failure.
-    else
-	"${ANNOTATESNPFROMGENBANK}"   -all "${ALL_ANNOTATIONS}" || true # This program returns an error regardless of success / failure.
-    fi
-
-    echo -e "Num_NotAnnotatedRegion\tAnnotatedNotProtein\tNum_NonSynon\tNum_Synon\tNS/S\tNSfractionOfAnnotated\tNumLoci\tNum_InAnnotatedGenomes\tNum_NotInAnnotatedGenome" > Annotation_summary
-    i=SNP_annotations
-    num_notInAnnotatedGenome=`grep  NotInAnnotatedGenome $i |  awk '  {print $1}' | sort -u | wc -l | awk '{print $1}'` 
-    num_UnAnnRegion=`grep  UnannotatedRegion $i |  awk '  {print $1}' | sort -u | wc -l | awk '{print $1}'`  
-    num_AnnNotProtein=`grep  NotProteinCoding $i |  awk '  {print $1}' | sort -u | wc -l | awk '{print $1}'`  
-    
-    NS_total=`grep -v LocusNum $i |  awk ' $3>0 {print $1}' | sort -u | wc -l | awk '{print $1}'` 
-    Num_loci=`grep -v LocusNum $i |  awk '{print $1}' | sort -u | wc -l | awk '{print $1}'` 
-    Num_loci_in_annotated=`grep -v LocusNum $i | grep -v  NotInAnnotatedGenome |  awk '{print $1}' | sort -u | wc -l | awk '{print $1}'` 
-    S_total=`perl -e "print ($Num_loci_in_annotated-$NS_total)"`
-    if [ $S_total  -gt 0 ]
-    then
-	NS_Sratio=`perl -e "print $NS_total/$S_total"`
-    else
-	NS_Sratio="inf"
-    fi
-    if [ 0 -lt $Num_loci_in_annotated ]
-    then 
-	NSfraction_overall=`perl -e "print $NS_total/$Num_loci_in_annotated"`
-    else
-	NSfraction_overall="inf"
-    fi
-    
-    echo -e "$num_UnAnnRegion\t$num_AnnNotProtein\t$NS_total\t$S_total\t$NS_Sratio\t$NSfraction_overall\t$Num_loci\t$Num_loci_in_annotated\t$num_notInAnnotatedGenome"  >> Annotation_summary
-    
-    
-    "${PARSEPROTEINANNOTATIONCOUNTS}" SNP_annotations > Protein_Annotation_counts
+    # cat genbank_from_NCBI.gbk.* | grep -v BioProject  > genbank_from_NCBI.gbk
 
     #run ParAnn
     "${PARANN}"
